name: Build

on:
  push:
    branches: [master]

jobs:
  buildAndDeploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # You can specify the Node version you need

      - name: Install dependencies
        run: npm i # Use npm ci to install exact versions from package-lock.json

      - name: Build Vue app
        run: npm run build

      - name: Upload to Server
        run: |
          sudo apt install lftp -y
          lftp -u ftpuser,1234 ftp://3.27.245.131 <<EOF
          mirror -R dist www/web-1
          bye
          EOF
